'use client';
import { candidates } from '@/lib/data';
import { Btn, ScoreRing, SectionHeader, Tag } from './ui';

export default function Shortlist({ onOpenCandidate }: { onOpenCandidate: () => void }) {
  const rankStyle = (rank: number) => {
    if (rank === 1) return { bg: '#FFF7E0', border: '#FFD700', color: '#B8860B' };
    if (rank === 2) return { bg: '#F5F5F5', border: '#C0C0C0', color: '#666' };
    if (rank === 3) return { bg: '#FFF0E8', border: '#CD7F32', color: '#8B4513' };
    return { bg: 'var(--blue-50)', border: 'var(--blue-200)', color: 'var(--blue-600)' };
  };

  return (
    <div>
      {/* Hero */}
      <div className="fade-up" style={{
        background: 'linear-gradient(135deg,var(--blue-900) 0%, var(--blue-700) 60%, #1151C8 100%)',
        borderRadius: '12px', padding: '28px 32px',
        color: '#fff', marginBottom: '24px',
        display: 'flex', alignItems: 'center', gap: '24px',
        position: 'relative', overflow: 'hidden',
      }}>
        <div style={{ position: 'absolute', right: '-20px', top: '-20px', width: '180px', height: '180px', background: 'radial-gradient(circle,rgba(0,212,255,0.18),transparent 70%)', pointerEvents: 'none' }} />
        <div style={{ fontSize: '48px', flexShrink: 0 }}>⭐</div>
        <div>
          <h2 style={{ fontFamily: 'Syne, sans-serif', fontWeight: 800, fontSize: '22px', marginBottom: '4px' }}>AI Shortlist — Full-Stack Engineer</h2>
          <p style={{ fontSize: '13px', color: 'var(--blue-200)' }}>Generated by Gemini AI · Screened 87 applicants</p>
        </div>
        <div style={{ marginLeft: 'auto', display: 'flex', gap: '24px', flexShrink: 0 }}>
          {[['87', 'Screened'], ['20', 'Shortlisted'], ['91', 'Top Score']].map(([val, label]) => (
            <div key={label} style={{ textAlign: 'center' }}>
              <div style={{ fontFamily: 'Syne, sans-serif', fontWeight: 800, fontSize: '28px' }}>{val}</div>
              <div style={{ fontSize: '11px', color: 'var(--blue-300)' }}>{label}</div>
            </div>
          ))}
        </div>
      </div>

      <SectionHeader title="Top 20 Candidates">
        <div style={{ display: 'flex', gap: '8px' }}>
          <Btn variant="outline" size="sm">Export CSV</Btn>
          <Btn variant="primary" size="sm">Export Report</Btn>
        </div>
      </SectionHeader>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,1fr)', gap: '18px' }}>
        {candidates.map((c) => {
          const rs = rankStyle(c.rank);
          return (
            <div
              key={c.id}
              onClick={onOpenCandidate}
              style={{
                background: '#fff', borderRadius: '12px',
                border: c.rank <= 3 ? `1.5px solid var(--blue-200)` : '1.5px solid var(--gray-100)',
                padding: '22px', transition: 'all 0.2s', position: 'relative', overflow: 'hidden',
                boxShadow: '0 2px 12px rgba(3,15,43,0.07)', cursor: 'pointer',
              }}
              onMouseEnter={e => { (e.currentTarget as HTMLDivElement).style.borderColor = 'var(--blue-300)'; (e.currentTarget as HTMLDivElement).style.boxShadow = '0 8px 48px rgba(3,15,43,0.22)'; (e.currentTarget as HTMLDivElement).style.transform = 'translateY(-2px)'; }}
              onMouseLeave={e => { (e.currentTarget as HTMLDivElement).style.borderColor = c.rank <= 3 ? 'var(--blue-200)' : 'var(--gray-100)'; (e.currentTarget as HTMLDivElement).style.boxShadow = '0 2px 12px rgba(3,15,43,0.07)'; (e.currentTarget as HTMLDivElement).style.transform = 'translateY(0)'; }}
            >
              {c.rank <= 3 && (
                <div style={{ position: 'absolute', top: 0, left: 0, right: 0, height: '3px', background: 'linear-gradient(90deg,var(--blue-500),var(--accent))' }} />
              )}

              {/* Rank badge */}
              <div style={{
                position: 'absolute', top: '16px', right: '16px',
                width: '32px', height: '32px', borderRadius: '50%',
                background: rs.bg, border: `2px solid ${rs.border}`,
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontFamily: 'Syne, sans-serif', fontWeight: 800, fontSize: '13px', color: rs.color,
              }}>#{c.rank}</div>

              {/* Header */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '14px', marginBottom: '14px' }}>
                <div style={{
                  width: '46px', height: '46px', borderRadius: '12px',
                  background: 'linear-gradient(135deg,var(--blue-600),var(--blue-400))',
                  color: '#fff', fontWeight: 700, fontSize: '18px',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                }}>{c.initials}</div>
                <div>
                  <div style={{ fontFamily: 'Syne, sans-serif', fontWeight: 700, fontSize: '15px', color: 'var(--blue-900)' }}>{c.name}</div>
                  <div style={{ fontSize: '12px', color: 'var(--gray-400)', marginTop: '2px' }}>{c.role} · {c.location}</div>
                </div>
                <div style={{ marginLeft: 'auto', display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
                  <ScoreRing score={c.score} />
                </div>
              </div>

              {/* Tags */}
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px', marginBottom: '14px' }}>
                {c.skills.map(s => <Tag key={s}>{s}</Tag>)}
                {c.gaps.map(g => <Tag key={g} gap>{g}</Tag>)}
              </div>

              {/* Reasoning */}
              <div style={{ background: 'var(--gray-50)', borderRadius: '8px', padding: '12px', fontSize: '12px', lineHeight: 1.6, color: 'var(--gray-600)', borderLeft: '3px solid var(--blue-300)', marginBottom: '14px' }}>
                {c.reasoning}
              </div>

              {/* Meta */}
              <div style={{ display: 'flex', gap: '12px', flexWrap: 'wrap', marginBottom: '16px' }}>
                <span style={{ fontSize: '12px', color: 'var(--gray-400)', display: 'flex', alignItems: 'center', gap: '4px' }}>🎓 <strong style={{ color: 'var(--gray-600)' }}>{c.education}</strong></span>
                <span style={{ fontSize: '12px', color: 'var(--gray-400)', display: 'flex', alignItems: 'center', gap: '4px' }}>💼 <strong style={{ color: 'var(--gray-600)' }}>{c.experience}</strong></span>
                <span style={{ fontSize: '12px', color: 'var(--gray-400)', display: 'flex', alignItems: 'center', gap: '4px' }}>📅 <strong style={{ color: 'var(--gray-600)' }}>{c.availability}</strong></span>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
